[package]
name = "demo_wgpu_compute"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.28.1", features = ["full"] }
wgpu = { version = "0.12.0", features = ["spirv"] }

[build-dependencies]
spirv-builder = "0.7.0"
